apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: bitcoin-secrets-provider
  namespace: bitcoin-namespace
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "bitcoin-core-secrets"
        objectType: "secretsmanager"

