name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to AWS ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 381491846288.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t 381491846288.dkr.ecr.us-east-1.amazonaws.com/bitcoin-core:latest .
        docker tag 381491846288.dkr.ecr.us-east-1.amazonaws.com/bitcoin-core:latest 381491846288.dkr.ecr.us-east-1.amazonaws.com/bitcoin-core:22.0

    - name: Push Docker image to ECR
      run: |
        docker push 381491846288.dkr.ecr.us-east-1.amazonaws.com/bitcoin-core:22.0

    - name: Configure kubectl with EKS
      run: |
        aws eks update-kubeconfig --name bitcoin-cluster --region us-east-1

    - name: Deploy to EKS
      run: |
        kubectl apply -f eks/deployment.yaml --validate=false
        kubectl rollout status deployment/bitcoin-core-deployment -n bitcoin-namespace

    - name: Verify Deployment
      run: |
        kubectl get pods -n bitcoin-namespace
        kubectl describe pods -n bitcoin-namespace

